name: test

on:
  push:
    tags:
      - '!v*'
    branches:
      - '*'
  pull_request:

jobs:
  unittests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup golang
        uses: actions/setup-go@v2
        with: 
          go-version: 1.16

      - name: unit tests
        run: make test